"""core schema

Revision ID: aab5910cca85
Revises: a73bc52e454a
Create Date: 2026-09-10 14:09:44.083094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab5910cca85'
down_revision: Union[str, None] = 'a73bc52e454a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("actor_type IN ('admin','system')", name='ck_audit_logs_actor_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active','disabled')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=32), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active','disabled')", name='ck_api_tokens_status'),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('dictionaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('lang_from', sa.String(length=8), nullable=False),
    sa.Column('lang_to', sa.String(length=8), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('word_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='disabled', nullable=False),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('imported_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("format IN ('mdict','stardict','ecdict')", name='ck_dictionaries_format'),
    sa.CheckConstraint("status IN ('enabled','disabled')", name='ck_dictionaries_status'),
    sa.ForeignKeyConstraint(['imported_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dict_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('word_lower', sa.String(length=255), nullable=False),
    sa.Column('phonetic', sa.String(length=255), nullable=True),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dictionary_id', 'word', name='uq_dict_entries_dictionary_word')
    )
    op.create_index(op.f('ix_dict_entries_word_lower'), 'dict_entries', ['word_lower'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source IN ('api','web')", name='ck_query_logs_source'),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_created_at'), 'query_logs', ['created_at'], unique=False)
    op.create_table('query_stats_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.String(length=10), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rate_limited_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'token_id', 'user_id', name='uq_query_stats_daily_dim')
    )
    op.create_table('token_vocab_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=True),
    sa.Column('phonetic', sa.String(length=255), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'word', name='uq_token_vocab_items_token_word')
    )
    op.create_table('vocab_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=True),
    sa.Column('phonetic', sa.String(length=255), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word', name='uq_vocab_items_user_word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab_items')
    op.drop_table('token_vocab_items')
    op.drop_table('query_stats_daily')
    op.drop_index(op.f('ix_query_logs_created_at'), table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_dict_entries_word_lower'), table_name='dict_entries')
    op.drop_table('dict_entries')
    op.drop_table('dictionaries')
    op.drop_table('api_tokens')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('audit_logs')
    op.drop_table('admins')
    # ### end Alembic commands ###
